(()=>{'use strict';
const token=new URLSearchParams(location.search).get('edit')||new URLSearchParams(location.hash.slice(1)).get('edit')||'';
const editing=token.length>0, esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let listings=[],hidden=[],filter='all',map,markers;
const $=id=>document.getElementById(id), msg=s=>{$('sync').textContent=s;};
async function api(path,method='GET',body){const r=await fetch('/api/'+path,{method,headers:{...(editing?{'Authorization':'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.message||'שגיאה בשרת');return d;}
async function refresh(){try{const data=await api('listings'+(editing?'?all=1':''));listings=data.items.filter(x=>!x.hidden);hidden=data.items.filter(x=>x.hidden);render();renderMap();renderHidden();document.querySelector('.stats .stat strong').textContent=String(listings.length);document.querySelector('header .nav a[href="#list"]').textContent=listings.length+' הנכסים';msg(listings.length+' נכסים מוצגים'+(editing?' · '+hidden.length+' מוסתרים':''));}catch(e){msg('לא ניתן לטעון נתונים משותפים. נסו לרענן את הדף. '+e.message);}}
function render(){const rows=listings.filter(x=>filter==='all'||x.category===filter);$('cards').innerHTML=rows.map(x=>`<article class="card"><div class="photos">${(x.photos||[]).map((p,j)=>`<a href="${esc(p)}" target="_blank" rel="noopener noreferrer"><img src="${esc(p)}" alt="${esc(x.title)} - תמונה ${j+1}" loading="lazy" onerror="this.closest('a').style.display='none'"></a>`).join('')}</div><div class="cardbody"><div><span class="number">${x.n}</span><span class="tag ${x.category==='פרויקט חדש'?'project':''}">${esc(x.category)}</span></div><h3>${esc(x.title)}</h3><div class="muted">${esc(x.area)}</div><div class="price">${esc(x.price)}</div><div class="detail">${esc(x.kind)}</div><div class="detail">${esc(x.garden)}</div><div class="detail">${esc(x.parking)}</div><p class="note">${esc(x.note)}</p>${x.source==='manual'?'<p class="muted">פרטים הוזנו ידנית - יש לאמת מול המודעה.</p>':''}<p class="photohelp">${(x.photos||[]).length} תמונות · גלילה לרוחב</p><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">מודעת יד2 המקורית ↗</a>${editing?`<button type="button" class="hide-btn" data-id="${x.n}">הסתרת נכס</button>`:''}</div></article>`).join('')||'<p class="muted">אין נכסים מוצגים בסינון זה.</p>';
$('comparison').querySelector('tbody').innerHTML=rows.map(x=>`<tr><td><a href="${esc(x.url)}" target="_blank" rel="noopener">${x.n}. ${esc(x.title)}</a></td><td>${esc(x.kind)}</td><td>${esc(x.price)}</td><td>${esc(x.garden)}</td><td>${esc(x.parking)}</td></tr>`).join('');}
function renderHidden(){$('hiddenList').innerHTML=hidden.map(x=>`<p>${x.n}. ${esc(x.title)} <button type="button" class="restore-btn" data-id="${x.n}">החזרה לרשימה</button></p>`).join('')||'<p>אין נכסים מוסתרים.</p>';}
function renderMap(){try{if(!window.L)throw 0;if(!map){map=L.map('map',{scrollWheelZoom:false}).setView([32.0838,34.975],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);markers=L.layerGroup().addTo(map);}markers.clearLayers();const pts=[];listings.filter(x=>Array.isArray(x.coord)&&x.coord.length>=2).forEach(x=>{const [lat,lon,scope]=x.coord;if(!Number.isFinite(lat)||!Number.isFinite(lon))return;pts.push([lat,lon]);L.marker([lat,lon],{title:x.n+'. '+x.title}).addTo(markers).bindPopup(`<b>${x.n}. ${esc(x.title)}</b><br>${esc(scope||'מיקום משוער')}<br>${esc(x.price)}<br><a href="${esc(x.url)}" target="_blank" rel="noopener">יד2 ↗</a>`)});if(pts.length)map.fitBounds(pts,{padding:[32,32],maxZoom:14});setTimeout(()=>map.invalidateSize(),150);}catch(e){$('map-fallback').textContent='המפה לא נטענה; פרטי הנכסים מופיעים בכרטיסים.';}}
if(editing){$('editor').hidden=false;document.querySelector('header .nav').insertAdjacentHTML('beforeend','<a href="#editor">עריכה</a>');}document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));filter=b.dataset.filter;render()}));
$('showHidden').onclick=()=>{$('hiddenList').hidden=!$('hiddenList').hidden;};
async function visibility(id,hidden){try{await api('listings/'+id,'PATCH',{hidden});await refresh();}catch(e){msg(e.message);}}
$('cards').addEventListener('click',e=>{const b=e.target.closest('.hide-btn');if(b&&confirm('להסתיר את הנכס לכל מי שצופה ברשימה?'))visibility(Number(b.dataset.id),true);});$('hiddenList').addEventListener('click',e=>{const b=e.target.closest('.restore-btn');if(b)visibility(Number(b.dataset.id),false);});
$('importForm').onsubmit=async e=>{e.preventDefault();$('importStatus').textContent='בודק קישור...';const url=$('link').value.trim();try{const d=await api('preview','POST',{url});if(d.duplicate){$('manualForm').hidden=true;$('importStatus').textContent='המודעה כבר קיימת ברשימה'+(d.hidden?' (מוסתרת - אפשר להחזיר אותה ברשימת המוסתרים)':'')+'.';return;}$('manualForm').hidden=false;$('manualForm').dataset.url=d.url;for(const [k,v] of Object.entries(d.fields||{})){const el=$('manualForm').elements.namedItem(k);if(el)el.value=String(v||'');}$('manualHint').textContent=d.blocked?'יד2 חסם את השליפה. יש למלא את פרטי המודעה ידנית לפני שמירה; לא נוצר נכס אוטומטי.':'נמצאו פרטים חלקיים מהדף. בדקו והשלימו אותם לפני שמירה.';$('importStatus').textContent=d.blocked?'נדרש מילוי ידני.':'בדקו את הפרטים לפני שמירה.';}catch(err){$('importStatus').textContent=err.message;}};
$('manualForm').onsubmit=async e=>{e.preventDefault();const f=e.target;const data=Object.fromEntries(new FormData(f));data.url=f.dataset.url;data.photos=data.photos.split(/\n/).map(x=>x.trim()).filter(Boolean);try{await api('listings','POST',data);f.reset();f.hidden=true;$('link').value='';$('importStatus').textContent='הנכס נשמר.';await refresh();}catch(err){$('importStatus').textContent=err.message;}};refresh();})();
